// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReminderState } from "./ReminderState";

export interface ClientState { client_uuid: string, data_path: string, reminders: Array<ReminderState>, }