// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReminderState } from "./ReminderState";

export type ClientCommand = { key: "AddOne", params: { value: number, } } | { key: "Add", params: { x: number, y: number, } } | { key: "SaveReminders", params: { reminders: Array<ReminderState>, } } | { key: "DelayReminder", params: { id: string, delay: bigint, } };