// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientState } from "./ClientState";

export type CoreResponse = { key: "Success", data: null } | { key: "ClientGetState", data: ClientState } | { key: "Sum", data: number };