// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ReminderState { id: string, name: string, is_active: boolean, wait_sec: bigint, duration_sec: bigint, }